[tasks.install]
command = "pnpm"
args = ["install"]

[tasks.run]
command = "pnpm"
args = ["dev"]

[tasks.resest]
command = "pnpm"
args = ["deploy:start"]


[tasks.clean]
clear = true
script = """
cargo clean
rm -rf ./contract/neardev/
rm -rf ./contract/target/
"""

[tasks.prepare]
script = """
rustup target add wasm32-unknown-unknown && rustup install 1.69 && rustup default 1.69 && cargo --version
"""

[tasks.build]
cwd = "./contract"
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "--release"]

[tasks.dev-deploy]
dependencies = ["build"]
script = """
#!/usr/bin/env zsh

set -e
WASM_PATH="$(find ./contract/target/wasm32-unknown-unknown/release -maxdepth 1 -name "*.wasm")"

near dev-deploy --wasmFile $WASM_PATH

if ! grep -q "^NEXT_PUBLIC_$(cat ./contract/neardev/dev-account.env)$" ./client/.env; then echo "NEXT_PUBLIC_$(cat ./contract/neardev/dev-account.env)" >> ./client/.env; fi
"""

[tasks.call]
script = """
#!/usr/bin/env zsh

set -e
[ -f ./contract/neardev/dev-account ] || (echo "Contract must be deployed"; false)
near call "$(<./contract/neardev/dev-account)" "$@"
"""

[tasks.call-self]
script = """
#!/usr/bin/env zsh

set -e
[ -f ./contract/neardev/dev-account ] || (echo "Contract must be deployed"; false)
near call "$(<./contract/neardev/dev-account)" "$@" --accountId "$(<./contract/neardev/dev-account)"
"""

[tasks.view]
script = """
#!/usr/bin/env zsh

set -e
[ -f ./contract/neardev/dev-account ] || (echo "Contract must be deployed"; false)
near view "$(<./contract/neardev/dev-account)" "$@"
"""